### ISSUE TITLE
Fix droparea being unresponsive on Firefox browsers

### ISSUE THREAD

**Issue by bearsy1** [krbz999/simple-loot-list#13]
I can't seem to be able to drag any item, whether from a compendium or from an imported item in the sidebar, to a token's loot list. When the cursor with an item is hovering over the drop area, it just shows the red circle-line symbol and nothing happens, no errors in the console and the list is not updated. I use tidysheet but I can't drag items with the default sheet either.

Is there something I'm missing (in terms of dependencies or steps to take for usage)?

Foundry 10.285 (Forge hosted)
DnD5e 2.0.3
Simple Loot List 10.0.4
Firefox 105.0.1 (64 bit)
& a bunch of other modules installed

**Comment by krbz999** [comment]
The current Foundry version is 10.286, though I don't think it is relevant. Please try updating.
- Then, could you try with all other modules disabled?
- If the issue persists, try in a different browser.

**Comment by bearsy1** [comment]
I'll make a backup and try it again. Fingers crossed!

**Comment by bearsy1** [comment]
Update.

I updated foundry to 10.286 and disabled all other modules apart from of course Simple Loot List, using Firefox. Still didn't let me drag and drop items.

However, using Chrome (latest version) under the same setup (all other modules disabled), it all worked fine. Strange. What's more, I activated the plethora of modules using Chrome and Simple Loot List still worked. It is indeed a browser issue.

I wonder why? I don't have strong feelings against other browsers, but I like and have gotten used to the feature set provided by firefox. I don't know if I'm asking for the moon here, but if it's not too much of a hassle, could this issue be addressed in this module with how it interacts with browsers (specifically being Firefox friendly)?

If not, that's okay too. If push comes to shove and I can come to terms with opening a different browser for my sessions, I _might_ do just that (or give up on the idea of using your awesome module haha).

**Comment by krbz999** [comment]
I think Chrome and Edge are the recommended browsers for Foundry.
However, I'll have a look at why this happens and see what can be done.

**Comment by krbz999** [comment]
A release has been pushed. I tested on Firefox and was able to reproduce the issue, and confirm that it worked afterwards. Thank you for reporting it. Please re-open this issue (or a new one), if the 10.0.5 release does not fix it.

**Comment by bearsy1** [comment]
Praise be! I don't know how you were able to get it sorted out so fast. Tried out the updated version and it works beautifully. 
I wish I could develop modules like you!
